### ISSUE TITLE
Reference PDF Not Downloading

### ISSUE THREAD

**Issue by pravintargaryen** [csev/ihts#3]
The Reference PDF ("[Paper: IEEE - JavaScript: Designing a Language in 10 Days](https://ihts.pr4e.com/columns/2012-02-Brendan-Eich-Copyright-IEEE.pdf)") in Week 4 (https://ihts.pr4e.com/columns/2012-02-Brendan-Eich-Copyright-IEEE.pdf) is not downloading and redirecting to home page asking for secret number. Even after the number is entered, download is not starting.

![Screenshot 2024-08-10 at 12-27-02 ](https://github.com/user-attachments/assets/fc7c5bc5-19ca-45d0-aa41-88cc3a685d36)

**Comment by csev** [comment]
Thanks - I think I fixed this - could you please check?

**Comment by pravintargaryen** [comment]
It's working now. Thanks Dr.Chuck

**Comment by csev** [comment]
Thanks
